name: Run Tests and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
     steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          pip install pytest

      - name: Run tests
        run: pytest

      - name: Reject if tests fail
        run: |
          if [ $? -ne 0 ]; then
            echo "Tests failed. Rejecting commit."
            exit 1
          fi

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Render CLI
        run: |
          curl -sL https://render.com/install.sh | bash

      - name: Configure Render CLI
        run: env render configure --token $env.RENDER_API_KEY

      - name: Deploy to Render
        run: env render up --force